//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProposalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal
    {
        public Proposal()
        {
            this.Result = new HashSet<Result>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Type { get; set; }
        public int MainProposer { get; set; }
        public string Co_Proposers { get; set; }
        public int ProcessingDepartment { get; set; }
        public string File { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ProposalType ProposalType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Result> Result { get; set; }
    }
}
