//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProposalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalType
    {
        public ProposalType()
        {
            this.Proposal = new HashSet<Proposal>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Proposal> Proposal { get; set; }
    }
}
